version: '3.7'
services:

  mariadb-services:
    image: mariadb:11.4.7-noble
    environment:
      - MARIADB_DATABASE=mariadb_project
      - MARIADB_PASSWORD=@LaforcetranquilleDuPain
      - MARIADB_ROOT_PASSWORD=@LaforcetranquilleDuPain_&15789351896631
      - MARIADB_USER=thibault
    ports:
      - 3306:3306
    networks: 
      - traefik_mspr-network
    volumes:
      - /opt/nfs/dev-projects/thilbaut_loubeyere/backend/mariadb-data:/var/lib/mysql      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_mspr-network
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.mariadb-public-http.rule=Host(`mariadb.jt.lordfire2222.local`)
        - traefik.http.routers.mariadb-public-http.entrypoints=http
        - traefik.http.routers.mariadb-public-http.middlewares=https-redirect
        - traefik.http.routers.mariadb-public-https.rule=Host(`mariadb.jt.lordfire2222.local`)
        - traefik.http.routers.mariadb-public-https.entrypoints=https
        - traefik.http.routers.mariadb-public-https.tls=true
        - traefik.http.services.mariadb-public-https.loadbalancer.server.port=3306


networks: 
  traefik_mspr-network:
    external: true
